dist: xenial

language: java
jdk:
  - oraclejdk11

install:
  #- mvn install  #   -Dmaven.javadoc.skip=true -B -V   -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8 -DskipTests=true 
  
script:
  #- mvn test    #-Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8

